---
- name: Installing Zsh and git
  apt: pkg=zsh,git state=latest force=yes #grr, why force???
  register: installation

# - name: Backing up existing ~/.zshrc
#   shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi
#   when: installation|success
#   sudo: no

- name: Cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: installation|success
  register: cloning
  sudo: no

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: cloning|success
  sudo: no

# Todo: Put repo path + destination path into vars
- name: Cloning zsh profile
  git: repo=https://github.com/waxmittmann/my-zsh-profile.git dest=/AnsibleInstall/zsh_profile

- name: Copying zsh profile into user root
  shell: cp /AnsibleInstall/zsh_profile/my_zshrc_profile.zshrc /home/vagrant/.zshrc

# Example git checkout from Ansible Playbooks
#- git: repo=git://foosball.example.org/path/to/repo.git
#       dest=/srv/checkout
#       version=release-0.22
